export const COLUMN_DEFS = [
  { key: 'ออร่าไวท์', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'ฉีดหน้าใส', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'Fat', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'Chanel (Lebss)', unit: 'ขวด', category: 'Skin', color: '#fce4ec' },
  { key: 'Juvelook', unit: 'cc', category: 'Skin', color: '#fce4ec' },
  { key: 'Hycoox', unit: 'Case', category: 'Skin', color: '#fce4ec' },
  { key: 'Rejuran ดำ/แดง', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'Skinvive', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'B Revive', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'Sculptra', unit: 'ขวด', category: 'Skin', color: '#fce4ec' },
  { key: 'HArmonyCa', unit: 'เข้ม', category: 'Skin', color: '#fce4ec' },
  { key: 'กราม', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'ลิฟท์', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'เหมาริ้วรอย', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'เหมาจมูก', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'หน้าผาก', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'หว่างคิ้ว', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'หางตา', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'ปีกจมูก', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'บันนี่ไลน์', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'ลิฟท์จมูก', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'โบคาง', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'โบตัว 50u', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'โบตัว 100u', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'โบตัว 150u', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'โบตัว 200u', unit: 'Case', category: 'Botox', color: '#e3f2fd' },
  { key: 'เหมาขวด 200U', unit: 'ขวด', category: 'Botox', color: '#e3f2fd' },
  { key: 'เหมาขวด 100U', unit: 'ขวด', category: 'Botox', color: '#e3f2fd' },
  { key: 'เหมาขวด 50U', unit: 'ขวด', category: 'Botox', color: '#e3f2fd' },
  { key: 'N คาง/ขมับ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'N อื่นๆ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'J คาง/ขมับ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'J อื่นๆ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'J Dolly Eyes', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'R คาง/ขมับ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'R อื่นๆ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'R Dolly Eyes', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'RL คาง/ขมับ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'RL อื่นๆ', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'RL Dolly Eyes', unit: 'cc', category: 'Filler', color: '#f3e5f5' },
  { key: 'Ultra', unit: 'shot', category: 'เครื่อง', color: '#e8f5e9' },
  { key: 'Oligio', unit: 'shot', category: 'เครื่อง', color: '#e8f5e9' },
  { key: 'Thermage', unit: 'shot', category: 'เครื่อง', color: '#e8f5e9' },
  { key: 'Consult BM', unit: 'Case', category: 'Consult', color: '#f5f5f5' },
  { key: 'Consult Mjaro รายครั้ง', unit: 'รายครั้ง', category: 'Consult', color: '#f5f5f5' },
  { key: 'Consult Mjaro รายแท่ง', unit: 'รายแท่ง', category: 'Consult', color: '#f5f5f5' },
] as const
export type TreatmentKey = (typeof COLUMN_DEFS)[number]['key']
export const CATEGORIES = ['Skin','Botox','Filler','เครื่อง','Consult','อื่นๆ'] as const
export const GROUP_COLORS: Record<string,string> = { Skin:'#fce4ec', Botox:'#e3f2fd', Filler:'#f3e5f5', เครื่อง:'#e8f5e9', Consult:'#f5f5f5' }